### ISSUE TITLE
Compiled RE2 camera release liks missed.

### ISSUE THREAD

**Issue by noonemodsforever** [FransBouma/InjectableGenericCameraSystem#103]
Hello. Where can I find compiled release version of Free camera foe Resident Evil 2? 
I cant find any link to release version there:
https://github.com/FransBouma/InjectableGenericCameraSystem/tree/master/Cameras/ResidentEvil2
And there:
https://github.com/FransBouma/InjectableGenericCameraSystem/releases/tag/RE2_100

Where is it able now?

**Comment by FransBouma** [comment]
I removed all of them and only added a few back. I removed most of them as I wanted to control more the distribution of the cameras as they're apparently used for commercial activities and I didn't like that much. After thinking a bit I readded the latest camera binaries. I'll re-add RE2's binary. I don't know whether it still works tho, if it breaks, then you're out of luck.

**Comment by FransBouma** [comment]
It's back again
