### ISSUE TITLE
Finding FOV

### ISSUE THREAD

**Issue by djavuch** [FransBouma/InjectableGenericCameraSystem#105]
Hi. I want to ask you how to find FOV correctly if the game doesnt have such an option? I read your article, I even tried the game on Wolfenstein demo, but in Rise of the Tomb Raider I cant find the value at all... I had a desire to take some new shots, but the way that remained a little uncomfortable. I'd be grateful for your help :)

**Comment by FransBouma** [comment]
(Please don't open issues like this in this repo)

ROTTR has a fov change when you zoom in with a weapon. That's usually the first go-to action to look for, i.e. you aim/zoom in with a weapon and the fov changes (when you zoom in, the fov value gets lower) so you can do the lower/higher scan combo to limit the number of values, by zooming in, search for decreased value once, then keep it zoomed in to scan for 'unchanged value', then let it go to go back to normal, scan for increased value once, then scan for unchanged value, rinse repeat
