### ISSUE TITLE
The screenshot take feature shouldn't create a new folder for every shot in singl-shot mode

### ISSUE THREAD

**Issue by FransBouma** [FransBouma/InjectableGenericCameraSystem#106]
When a single screenshot is taken, the code simply re-uses the pipeline for panoramas however that creates a new folder for each shot which is a bit ridiculous.

**Comment by vczh** [comment]
Just found you do create bugs for yourself! I have never done in this way, instead I keep all of them in a MD file, because that's too many of them.

**Comment by FransBouma** [comment]
Heh :) Yeah this is easier if there aren't that many as you can track them with commits too (refer to them so you get a bit of tracability back). for hobby stuff like this, it's not that important, but alas, am used to it so why not use it here too :)

**Comment by FransBouma** [comment]
This has been implemented in recent camera (SWJFO)
