### ISSUE TITLE
Cutscene crashes.

### ISSUE THREAD

**Issue by HowlingDoll** [FransBouma/InjectableGenericCameraSystem#110]
Greetings.

Not sure how to report a problem over here, so yeah.
Game crashes everytime in the middle of any cutscene, yes in the middle. For example when Claire is talking with Brian Irons by the phone after finding all power parts and the cutscene switches from Claire to Brian Irons, crash. Doesn't really matter if I am running game with or without any mods, if IGCSInjector is on - crash. I've verified files via Steam, still the same story. IGCSInjector works perfectly but out of cutscenes for some reason. It's been for a week so far, I guess? There wasn't any single issue before though. Any ideas?

**Comment by FransBouma** [comment]
Nope. All I did was fixing the camera to the latest patch. I also got a crash without the camera in the startup sequence btw. So I have no idea what's wrong.

**Comment by HowlingDoll** [comment]
Well, you know all chashes began only after I've downloaded the new version of IGCSInjector.
Where I can get the previous version by the way?

**Comment by FransBouma** [comment]
the injector just injects the dll. The previous version doesn't work anymore as they've updated the game and introduced new code which broke the original one.

**Comment by HowlingDoll** [comment]
I see. Well then, I have no clue what could be a problem. Thanks for the response.

**Comment by halo1089** [comment]
> the injector just injects the dll. The previous version doesn't work anymore as they've updated the game and introduced new code which broke the original one.

I really hope you will be able to figure this out, I know you don't have to, but man, those black bars at 16:10 aspect ratio really are not something pretty to look at.

**Comment by FransBouma** [comment]
I won't look at it again, so you have to deal with it.
