### ISSUE TITLE
resident evil 2 game crashes when playing in game cut scenes

### ISSUE THREAD

**Issue by lisigang1994** [FransBouma/InjectableGenericCameraSystem#111]
every time the game playing a CG it will crash and quit to desktop.  I don't know whether others have the same issue. if anyone can tell me how to solve it thanks a lot.

**Comment by FransBouma** [comment]
I don't know what causes it, more people have reported it, no idea.

**Comment by HowlingDoll** [comment]
Well, hopefully you will figure it out in the future. I've asked like 3-4 of my friends to test it out and they have exactly the same issue.

**Comment by FransBouma** [comment]
Not sure what you're trying to accomplish but replying in various threads doesn't make me fix it, **if I can fix it at all**, as it's not a problem I introduced. The game crashes, that sucks, but I can't help that. 

I have uninstalled the game after I updated the camera tools and as I won't replay it again, I won't redownload it again and look at it. It's not as if I have a lot of time and nothing to do :(
