### ISSUE TITLE
Pic taking causes GreedFall to freeze up

### ISSUE THREAD

**Issue by BelovedPoison** [FransBouma/InjectableGenericCameraSystem#114]
Hello, 
Um I apologise if I'm doing this wrong but I'm very new to all this, though not new to using IGCS for GreedFall as I've had it for a while now.

Anywho, I loaded up GreedFall today and I've noticed when I take a shot, suddenly the game slows right down and kinda freezes. I can turn igcs off and on and things but it won't show I've done and I cannot move the camera around or continue until I press the windows button to go out of GreedFall and then back into it. Once I do this it works fine, but it's frustrating having to do this. 

I've recently upgraded a few things in my comp such as a much better graphics card and doubling my ram but nothing else has changed so I'm unsure if it's my comp, the game or the camera causing issues. 

Do you have any idea how I may sort this without having to resort to my above method? 

Sorry to bother you but also thank you for this camera system, I love taking GreedFall shots so I really appreciate being able to frame them how I want instead of how the same says. :)

**Comment by FransBouma** [comment]
Greedfall sometimes runs into crashes when you increase the resolution and then take a shot. If I remember correctly I used nvidia DSR to set the game into a higher resolution and played/shot it using that.
