### ISSUE TITLE
Binaries for HITMAN 2016 Camera Hack

### ISSUE THREAD

**Issue by J0E9411** [FransBouma/InjectableGenericCameraSystem#115]
Hello. Can would it will be possible for you to upload the last binaries for HITMAN 2016 Camera Hack? 

Thanks.

**Comment by FransBouma** [comment]
I can, but to my knowledge they don't work anymore

**Comment by FransBouma** [comment]
I've readded it, but as said: it's likely it won't work anymore. I won't fix it anymore, so if it doesn't work, that's too bad.
