### ISSUE TITLE
Failed to create directX device and swapchain!

### ISSUE THREAD

**Issue by Evil-Raveen** [FransBouma/InjectableGenericCameraSystem#117]
https://i.imgur.com/29oFpGr.jpg
Run the game as Administrator https://i.imgur.com/rd3bg9O.jpg
Failed to create directX device and swapchain! https://i.imgur.com/Z2Nn03N.jpg

**Comment by FransBouma** [comment]
Use: https://framedsc.github.io/GeneralGuides/universal_ue4_consoleunlocker.htm instead, it surpasses this camera and has all the features this one has too, I ported everything over.

**Comment by Evil-Raveen** [comment]
thanks
