### ISSUE TITLE
Steam overlay

### ISSUE THREAD

**Issue by ForgottenKryos** [FransBouma/InjectableGenericCameraSystem#119]
Hi! When i Enable Camera (Insert) Steam overlay doesn't work.
How can i fix this?
Want take more screenshots in Steam, but don't can.

**Comment by FransBouma** [comment]
which game/camera? 
Anyway, I haven't heard of this before, how do you know the overlay doesn't work?

**Comment by ForgottenKryos** [comment]
I use function Enable / Disable Camera (Insert) in game. 
When i try take screenshot or use TAB+SHIFT, Steam overlay don't react.

**Comment by FransBouma** [comment]
I asked 'which game/camera' ? 
It might be due to imput blocking. If you press `numpad .` it will enable input to the game again. pressing a key should then work ok.

**Comment by ForgottenKryos** [comment]
Please, just take a look. If you do not understand what I mean.
[https://youtu.be/96_LZ2LvZ88](url)

**Comment by FransBouma** [comment]
I understand what you mean, you haven't tried what I said, nor answered my question. Did you try `numpad .` to enable keyboard input?

**Comment by ForgottenKryos** [comment]
Omg, i don't see "." symbol in you reply!
And don't understand how activate / diactivate Numpad should help me!
Yeah, now it works and i can takes screenshots, thanks!

**Comment by ForgottenKryos** [comment]
Sorry, i really don't see "." symbol in you reply.
Thank you.

**Comment by FransBouma** [comment]
By default I block the input of the device you choose for the camera movement to the game. So if you choose 'gamepad' and you enable the camera, gamepad input is blocked, but not keyboard/mouse. You can switch that on/off with `numpad .` by default (you can configure which key in the client GUI). By default both keyboard/mouse and gamepad are camera devices, so if you enable the camera, keyboard input is blocked to the game so the game never sees the keys you press. 

`Numpad .` is the key next to `Numpad 0`, the dot/del key on the numpad.

**Comment by ForgottenKryos** [comment]
> By default I block the input of the device you choose for the camera movement to the game.
I see.
> `Numpad .` is the key next to `Numpad 0`, the dot/del key on the numpad.
Yeah, now i understand what key you mean.
Thank you so much! And for this mod too!
