### ISSUE TITLE
MGSV: Ground Zeroes support for MGS5 camera

### ISSUE THREAD

**Issue by kazblox** [FransBouma/InjectableGenericCameraSystem#122]
The following answers are likely one of the following:
- "no :)"
- "never :)"
- "will not consider :)"
- "no, and no ifs, ands, or buts :)"

...but a question that could be asked is a question worth asking. Is support for Ground Zeroes doable, and if so, could you consider doing such in your spare time? Would help slightly with graphics debugging and analysis.

**Comment by FransBouma** [comment]
Anything's possible, but I'm not going to invest time in this. If the MGS5 camera doesn't work then, sorry, but it's not gonna happen :)

**Comment by kazblox** [comment]
Without even looking at why it obviously doesn't work due to how Ground Zeroes lacks features such as dynamic weather and is running on a very earlier version of the game's engine.
OK then!

**Comment by FransBouma** [comment]
> 
> 
> Without even looking at why it obviously doesn't work due to how Ground Zeroes lacks features such as dynamic weather and is running on a very earlier version of the game's engine.
> OK then!
> 
> It's also compiled with an earlier version of Visual Studio, so the assembly will obviously be different.
> Just WHY are you not going to invest time in this without being so vague? **Don't give yet another inconclusive response or else.**

Or else **what**... is that a threat?

Why should I invest time in making a camera for a game 1) I don't own (ground zeros) 2) I don't have intention to play and 3) I don't have MGS5 installed anymore?

Do you realize I do this in my spare time? You're now demanding me to invest time for **you**, someone who posts messages like 'Don't give yet another inconclusive response or else'...

**Comment by kazblox** [comment]
_Or else_ I will keep criticizing the way you respond. This is not a threat, this is constructive criticism of your mindset.
I was asking nicely, and on the very first reply, you were pushing buttons. All you had to do was state exactly why you don't want to bother, and then I would let you be.

> Do you realize I do this in my spare time? 
That's why I said "could you consider doing such **_in your spare time?_**" You didn't even read most of my message. That shows that you are incompetent.

**Comment by FransBouma** [comment]
Oh ffs.

**Comment by nwoolls** [comment]
Someone's getting glitter bombed...

**Comment by ramonsmits** [comment]
LOL, calling @FransBouma  incompetent...... He clearly doesn't know you :-)

**Comment by FransBouma** [comment]
Ok, I've locked the thread as it's run its course I think :) Let's enjoy life instead of bicker about irrelevant shit, the world is already in an enough depressing state as it is, m'kay? 👍
