### ISSUE TITLE
cannot take screenshot suddely

### ISSUE THREAD

**Issue by sendu666** [FransBouma/InjectableGenericCameraSystem#123]
Been using it for re3 2020, it was working well before, suddenly I could't take screenshot (using steam in-game screenshot key)every time I use this camera,then I could take screenshot again once the camera disabled, what might cause this?

**Comment by sendu666** [comment]
oh never mind I figured out, it';s the "."

**Comment by FransBouma** [comment]
Indeed. 😄 By default I block all input :)
