### ISSUE TITLE
while using the camera , time stopped in the game.

### ISSUE THREAD

**Issue by SaldaxGaming** [FransBouma/InjectableGenericCameraSystem#125]
Heey Mate,

at first great camera system.
I just want to know if its possible to use the camera tool in Dishonored 2 like in Assassins Creed? Dishonored 2 is just an example, there the time while using the camera tool stopped (freeze). For screenshots its awesome but if i wanted to record an video its not that good :) 
Did i missed something toset it corectly up for an freecam without game time stopped or is that not possible because also wth ansel the game time stopped? 
Thanks for your time!
and have a good day with friendly regards Saldax.

**Comment by FransBouma** [comment]
The dishonored 2 camera tools utilize the ansel API, so basically call the same functions that ansel will call too, which pause the game when the session (enable camera) starts. In theory I could reverse engineer the whole pipeline and perhaps dig up the pause function but I don't have the game installed anymore so I'm sorry but I won't work on this anymore. 

I understand what you mean tho, and the dishonored 2 tools were more of a quick hack to get a camera working and not based on true reverse engineering the engine like I normally do, so they're a bit limited. So it's not you, it's just not supported in the camera tools :)
