### ISSUE TITLE
Control_DX12 crash when enabled cam

### ISSUE THREAD

**Issue by SS4K** [FransBouma/InjectableGenericCameraSystem#126]
hey Frans

i tried to updating the script for enabling the cam but no luck 

HUD/puase updated Successfully 

i appreciate if you ever have the time to updated

**Comment by FransBouma** [comment]
Won't be updated, sorry

**Comment by FransBouma** [comment]
The last updated table is here: perhaps you have an outdated one: https://framedsc.github.io/GameGuides/control.htm

**Comment by SS4K** [comment]
i already have latest ver , i think it was working fine on game ver 1.07 , game now on 1.10
anyway thanks for responding , and i always loved you work 
✌

**Comment by SS4K** [comment]
i Successfully updated the table 
 except the Hotsampling i didn't test it , it requires additional files to install iirc and i am not interested in it tbh

if you want me to upload the table let me know

**Comment by FransBouma** [comment]
Hotsampling doesn't require additional files tho. You just have to make sure you use the right offsets

**Comment by SS4K** [comment]
that's unfortunate , i just did quick update 

i properly going to updated when the final DLC drop in Q3

anyway if ever want the table just let me know 👍

**Comment by FransBouma** [comment]
thanks! will do :)
