### ISSUE TITLE
Devil May Cry 5 Can't attack the problem

### ISSUE THREAD

**Issue by jimb55** [FransBouma/InjectableGenericCameraSystem#127]
Hello, I have two questions.

1 when I was playing DMC 5, I opened Camera and found that the character could only walk forward and could not be attacked by the monster and shoot the monster (the character's chop can hit, but can't shoot the monster)

2 once you move a distance or jump, the character will be stuck in place (in air status)

**Comment by FransBouma** [comment]
Maybe they've updated the game and the camera no longer works correctly, no idea. I don't have the game installed anymore so won't look into it, sorry.
