### ISSUE TITLE
CP 2077 various issues when player is on a bike

### ISSUE THREAD

**Issue by FransBouma** [FransBouma/InjectableGenericCameraSystem#130]
v1.0.1a
- camera is different, doesn't work when on a bike
- FoV doesn't work in pm when on a bike
- HUD toggle doesn't work in PM when on a bike. It does work in-game

**Comment by FransBouma** [comment]
3rd instance of AOB for camera interception is the one triggered when you're on a bike.
If the PM is opened before being on a bike, all is OK. 
If not, things won't work.

**Comment by DorianSoloviev** [comment]
Please help, my V's head is dissapear..... and... I don't know why.... :|

**Comment by FransBouma** [comment]
Don't add your message to a closed issue, open a new one next time.
when enabling the camera in normal gameplay there's no head, that's normal. The head only appears when you open photomode. You can then enable the camera and move around
