### ISSUE TITLE
Game now crashes after running

### ISSUE THREAD

**Issue by felautumn** [FransBouma/InjectableGenericCameraSystem#131]
Hello, I ran cyberpunk and then ran the IGCSClient.exe and the game now crashes when trying to load the main menu.

I couldn't find any process running related to the 'client' (no client actually popped up after running it) yet every time I open Cyberpunk now, it crashes.

I followed the readme correctly.

**Comment by FransBouma** [comment]
Not sure what you were doing, but the game doesn't crash by just running the client. You click the Inject DLL button and it crashes then? Do you run the 1.0.5 update of the game and the latest versoin of the tools (1.0.2) ?

**Comment by felautumn** [comment]
I'm running the latest update of the game, 1.0.6, which is probably why it's broken.

**Comment by felautumn** [comment]
I did inject the dll after selecting the game process from the drop down though, I just have a terrible memory. The client did load, it just closed after the game crashed.

**Comment by felautumn** [comment]
Is there a way to fix this, what dll's did it inject and can I remove them?

**Comment by FransBouma** [comment]
If there's an 1.0.6 update and it broke the tools they'll be fixed. I don't recall there being a 1.0.6 tho.

**Comment by felautumn** [comment]
Is there a way to fix my game without redownloading the entire thing? Can I delete the injected dll's? I wouldn't know what those were or where they are.

**Comment by FransBouma** [comment]
If you don't inject the dll then nothing is affecting your game. There's no 'auto inject' going on from my tools, I never do that. So it must be something else you installed/downloaded.

**Comment by felautumn** [comment]
I did inject the DLL... and now it crashes upon running the game.

Look, it's not my fault you can't read properly, I made it very clear what I did and what the issue what. I've uninstalled the game and not going to bother with it anymore.

**Comment by felautumn** [comment]
Thanks for closing it early before you could determine whether I still had issues with it though, real thoughtful of you.

**Comment by felautumn** [comment]
I literally wrote "I did inject the dll after selecting the game process from the drop down though"

How could you come to the conclusion that I didn't? Walking around like a deer in headlights, yikes.

**Comment by felautumn** [comment]
Good luck with your broken cameras.

**Comment by FransBouma** [comment]
> I did inject the DLL... and now it crashes upon running the game.

so does it crash after you injected it every time? Or also when you don't inject the dll? That's unclear from that sentence alone. In any case, you're the first reporting this so it might be something else (like ... the game itself? Some mods? reshade? Something else?) 

> Thanks for closing it early before you could determine whether I still had issues with it though, real thoughtful of you.

Yeah I'm obligated to answer and help you till it's resolved, right? It's a free mod I wrote in my spare time. Get off your high horse.
