### ISSUE TITLE
[Feature Request/Suggestion] Depth Map Export

### ISSUE THREAD

**Issue by Michael-Thibault** [FransBouma/InjectableGenericCameraSystem#134]
I realize this may be a huge ask and not feasible, but since you're digging-around like this figured I'd ask anyway.

There is great potential in using a depth map to get more control in post-processing, specifically in the application of depth-of-field effects (since Cyberpunk 2077's built-in one is pretty terrible in quality, and has truly horrifying interactions with things like hair).

**Comment by FransBouma** [comment]
You can use reshade for that :) With the display depth shader you can visualize the depth buffer and e.g. take a screenshot.
