### ISSUE TITLE
CP 2077 character begins to fall through the world

### ISSUE THREAD

**Issue by ShockFactor** [FransBouma/InjectableGenericCameraSystem#135]
hi! this camera is awesome! it was working really well for a few hours, but im not sure what i did to cause this? 

once you fly your camera far enough away from your character's origin, the screen will turn slightly monochrome-ish with a blurry vignette as if s/he's losing health. when you return to your character, you'll find s/he has slipped through the world. My character will just be clipping into the ground, I can double jump to return back onto the surface (but otherwise the game will reset you regardless)

this wasnt happening initially. im not sure what changed, i did reload the game and re-inject and it still happened where the screen loses some color to reflect your character's situation (otherwise i wouldnt mind leaving that plane of existence)

sorry if this has already been posted, im a github novice! great work btw!

**Comment by FransBouma** [comment]
I move the camera, I leave any player stats alone, so not sure what happens, it might be the game checks up on the camera after a while and does a check, but frankly I have no idea. If you want to avoid this, perhaps try to pause the game before flying far away?
