### ISSUE TITLE
CP2077 -- please adjust player location to resolve some lingering issues with cam

### ISSUE THREAD

**Issue by AscendChina** [FransBouma/InjectableGenericCameraSystem#136]
So the camera works great but couple issues.... most notable is that when I start roaming at a far enough distance away from the player (since the player is static and not moving when the camera free roams) the game has an issue where the cars and pedestrians become ugly 2D sprites... it just looks awful especially close up to them... like a cartoon... another issue is I hit an invisible radius and the world turns black and white and then the player starts to lose health and die if the camera travels too far from the player origin.... I believe these two issues can all be resolved if the player location can somehow be made to match the camera location, like a noclip of sorts, where the game always thinks the player is also moving with the camera hence it will not use 2D sprites for cars/pedestrians 

Would be really be great is if there was a button we can press and it drops the player to that location. So I cam use the camera to fly to the top of any skyscraper, then I press a button and I'm out of camera mode but my player gets spawned and dropped on top of the skyscraper and now I can walk around freely and roam the top of the skyscraper or structure itself! 

Also, a third issue is when even I'm at the player origin, if I navigate high enough to take a "big picture" view of the world in CP2077, I noticed in far away areas there are patches of darkness, pitch black areas that aren't rendered by the engine.... this looks incredibly jarring and kills immersion, and when I travel in camera close enough to these pitch black areas they then become filled in and rendered.... so its basically some sort of draw distance glitch where things that are in the camera fulcrum don't get drawn at all.... this is likely a bug with the game, because even without using this tool, whenever I climb to very high places, this also happens.... so the game isn't drawing everything it should be drawing because the draw distance is somehow set artificially low.... but even when I skydive in other games like GTA, or go high on watchdogs, fly plane in Far Cry 5 etc etc I don't see this issue, meaning its unique only to CP2077 and the way REd Engine is rendering stuff...

**Comment by FransBouma** [comment]
I can't change how the game does its LOD filtering. So I'm sorry but I'm not going to implement this.
