### ISSUE TITLE
Is there a generic injection for Unreal Engine 4?

### ISSUE THREAD

**Issue by AscendChina** [FransBouma/InjectableGenericCameraSystem#137]
Many games are using Unreal Engine 4, especially a lot of indie titles and smaller games.... for example there is particular a Titanic game that I'm interested in using this camera mode for...

https://www.titanichg.com/

Is there a generic cam system specifically for games made in UE4

**Comment by FransBouma** [comment]
yes, I made one for UE4: https://framedsc.github.io/GeneralGuides/universal_ue4_consoleunlocker.htm

Not sure if that game is supported tho, but you could give it a try ;)
