### ISSUE TITLE
How take a photo in 2077?

### ISSUE THREAD

**Issue by ckvir** [FransBouma/InjectableGenericCameraSystem#138]
Hi Frans,

Thanks for your tool ( Cyberpunk 2077 v1.0.4+ camera tools )
But I can not take a photo when i pressed "insert" to enable Camera System mode  in game?
Is there have another method?

**Comment by FransBouma** [comment]
You can take a shot with e.g. msi afterburner or reshade (https://reshade.me, which also gives effects), or nvidia overlay (alt-f1).
