### ISSUE TITLE
Head problem

### ISSUE THREAD

**Issue by DorianSoloviev** [FransBouma/InjectableGenericCameraSystem#139]
Sorry, 'im new here.... 

Well, i want a take a picture when my V's is.... with a joytoy... and his head is disappered.... i moved the camera after i opened the photo mode. :\

**Comment by FransBouma** [comment]
Yeah sorry that's not gonna work. The game doesn't render a head in those scenes, with or without photomode... there's no way to force the game to render the head at the moment...
