### ISSUE TITLE
Screenshot through Steam

### ISSUE THREAD

**Issue by panicthescaredycat** [FransBouma/InjectableGenericCameraSystem#140]
I'm trying to takte 4k screenshots of Cyberpunk 2077, using the Steam Hotkey (F12) But it's not letting me. Also the hotkeys are all numpad, unfortunately I have a 60% keyboard. I changed the hotkeys but they don't seem to work at all.. it doesn't change.

**Comment by FransBouma** [comment]
I use F12 as well, works fine? For keybindings you have to enable keyboard input (normally bound to `numpad .`) to unblock the input, otherwise it will block a normal keybpress

**Comment by panicthescaredycat** [comment]
I don't have a numpad though... I tried to change the keybindings but they don't seem to change, Because (Example) If i changed Numpad . to PageDown, and removed keybind on the original Pagedown keybind. When I go back into the game, Press Pagedown, it does what the original keybind was set to before, not what the new keybind is.. Does that make sense? x.x

**Comment by FransBouma** [comment]
The numpad . action (Block input to game) is only active when the camera is enabled. So if you want to test that, you have to enable the camera first, then press that key. I tried, it works fine, keybinding changes are followed and work as expected.
