### ISSUE TITLE
Hotsampling since 1.1

### ISSUE THREAD

**Issue by NobuyukiMatsuhisa** [FransBouma/InjectableGenericCameraSystem#141]
Since the CP77 1.1 update, I have found that Hotsampling will no longer actually resize the game window. The camera client says the game window has been resized, but when a screenshot is taken, the image is in the original resolution. 

Simply put, Hotsampling seems to no longer have any effect. It was working perfectly before the game update.

**Comment by FransBouma** [comment]
This is caused  by a bug in Cyber Engine Tweaks. You have to wait for them to release a new update or build the code from source from their repo (https://github.com/yamashi/CyberEngineTweaks). If you're not using Cyber Engine Tweaks, then I don't know, but it's highly likely that.
