### ISSUE TITLE
Cyberpunk Hotsampling

### ISSUE THREAD

**Issue by Aquelyras** [FransBouma/InjectableGenericCameraSystem#142]
Hey, since the 1.1 Patch if got an Issue with the Hotsampling in CP2077. If i Switch the Resolution it only Screens everything in 1920x1080 instead of my Choosen Resolution if i use the Spacebar from CP Photomode. It also Change the Complete Camera Position after Hotsampling it in the Direction of the Left Corner. Also used Nvidia Capture before and it wont Open anymore while using the Hotsampling tool. Afterburner just let me Screen in my Base Resolution of 4k/1440p not the Changed Resolution. You got any Tips to fix this ?

**Comment by FransBouma** [comment]
Bug in Cyber Engine Tweaks. You have to wait for their next release which contains the fix, or join my patreon and download a temp build from there
