### ISSUE TITLE
How do you even install this?

### ISSUE THREAD

**Issue by riancharlie** [FransBouma/InjectableGenericCameraSystem#144]
The readme doesnt exactly say anything for cp77 , and there is no dll file to inject or no exec in the cyberpunk folder kinda got no clue what to do although im probably missing a major detail but idk

**Comment by FransBouma** [comment]
Binaries aren't on this site anymore. Binaries are on my patreon: https://patreon.com/Otis_Inf, the url that is on the readme page of the camera.
