### ISSUE TITLE
Patreon Subscription Required?

### ISSUE THREAD

**Issue by aggere1** [FransBouma/InjectableGenericCameraSystem#145]
Do I understand correctly that you require users to pay for a subscription to have access to latest binaries for cyberpunk camera tools?  This is not a criticism.  I'm seeking to understand if this is a requirement.  I don't have the resources to support subscribing to your patreon, so am concerned I will no longer be able to use this tool.  Thank you.

**Comment by FransBouma** [comment]
Yes this is a requirement now. I've moved all my binaries to my patreon. I gave away the Cyberpunk camera tools for free for more than a month, and maintenance starts to taking a lot of time hence I no longer give it away for free (normally cameras I make are paid from the start btw). 

Subscribing also gets you 2 other things btw: Cyberlit, a paid custom light tool which allows you to create custom lights in a scene and a cheat table to control lookat camera (head, eyes) for V. You can sub for 1 month and download all cameras, they keep on working after the month, till CDPR decides to update the engine and break things of course ;)
