### ISSUE TITLE
Build Guide

### ISSUE THREAD

**Issue by Lagicrus** [FransBouma/InjectableGenericCameraSystem#146]
Is it possible to give up to date instructions on how to try building these projects ourselves? The best I can find is a 3 year old blog post from yourself.
Whilst it is very detailed, it is beginning to get old and some bugs seem to happen on the build.

Thanks

**Comment by FransBouma** [comment]
Everything's possible, but I'm not going to do that, sorry :). There's also not that much to say: the guide I wrote has instructions how to set up masm, which is the biggest pain point. VS2019 will build some of them just fine (but older ones needs some adjustment/migration), perhaps you need to change `default` into `defaultValue` as it's clashing with the newer C++ version used in vs2019, and change `BYTE` to `uint8_t` as it's no longer used as a type in newer SDKs. 

The code in this repository is basically outdated. All my newer cameras aren't in this repo, except cyberpunk but this cp camera isn't going to be updated. I kept it open as links are pointing to this repo, but no plans to change code in this repo. 

For binaries, sub to my patreon: https://patreon.com/Otis_Inf.
