### ISSUE TITLE
Time dilation in Hitman 2

### ISSUE THREAD

**Issue by KillerRussia** [FransBouma/InjectableGenericCameraSystem#147]
Hello, little brother. In Hitman 2016, there was a time dilation in the free camera and it was divine. Currently, this feature does not work in Hitman 2. The game does not pause. Please tell me, is it possible to do this? if so, to which account should I transfer my money?)) I am ready to become a sponsor. From Russia with love " Laborantskaya@yandex.ru "

**Comment by FransBouma** [comment]
It might be present in hitman 2 but I don't have hitman 2 and no plans to build tools for that game, sorry :) The reason is mostly that they update their builds every week and it's tedious to patch the tools every week for their new update. At least that was the case with hitman 1
