### ISSUE TITLE
Devil may cry 5 camera tools issue on pc windows 10 (PLEASE HELP Fransbouma)

### ISSUE THREAD

**Issue by hustle4123** [FransBouma/InjectableGenericCameraSystem#149]
devil may cry 5 camera tools are working fine but the camera is not moving at all. FOV, block input to game, pause game, etc, All these are working fine except for the camera...its not moving at all. I've been trying to make it work since two days but the camera does not move at all after enabling camera , it's just stuck at one place but the characters moving and when i block input to the game....still the camera is stuck....PLEASE HELP. Thank you @FransBouma

**Comment by FransBouma** [comment]
Camera will be updated soon (to the new igcs system), binaries will be available on my patreon https://patreon.com/Otis_Inf. This sourcecode is archived, it won't be updated.

**Comment by hustle4123** [comment]
does the dmc 5 camera tool need denuvo version or the denuvo removed version of game exe file ?....i have a cracked version of the game...would these camera tools work on the cracked version ?

**Comment by FransBouma** [comment]
My cameras are built with the official game versions. Whether they work on a cracked version is something I don't know and I also don't support piracy so if you use a pirated version of the game, then I think you're out of luck

**Comment by hustle4123** [comment]
its really strange that everything from your dmc 5 camera tool is working but it is only the camera that is not moving at all. But anyways..Thank you sir!!
