### ISSUE TITLE
Camera stuck

### ISSUE THREAD

**Issue by NoobGotPro** [FransBouma/InjectableGenericCameraSystem#152]
The camera worked great the first time I used it but the next few times it worked but was only stuck in one place and I couldn't figure out how to move it

**Comment by FransBouma** [comment]
All cameras in this repository are considered archived.

**Comment by a2nath** [comment]
What's the posting in your patreon page for TR 2013? What's the membership level needed?

**Comment by FransBouma** [comment]
> Where's the posting in your patreon page for TR 2013? What's the membership level needed?
> 
> I can't compile the Visual Studio solution due to syntax error with .asm file. Says pop ebp is not an instruction

Like patreon says, 5 euros, you get all the tools I made, including uuu v4&5.
