### ISSUE TITLE
Fixed table for Control with HDR+Ultrawide+DLSS+RT Patch/Mod please?

### ISSUE THREAD

**Issue by itsTyrion** [FransBouma/InjectableGenericCameraSystem#154]
Hi. 
There's this mod https://community.pcgamingwiki.com/files/file/2581-control-hdrultrawidedlssrt-patch/ that adds HDR, DLAA, updates DLSS (and allows FSR2 injection!!)...
When using it, your CheatEngine Table no longer works due to game's .exe files and a lot of DLLs being replaced (all addresses are red in CE). 
Would you consider making a version for it?

**Comment by FransBouma** [comment]
Oh my cheat table doesn't work anymore for a long time I think. :) Nowadays the debug tools offer way more functionality. So, no I'm not considering fixing it, sorry.
