### ISSUE TITLE
Failed to get device from Hooked Swapchain

### ISSUE THREAD

**Issue by Fael78BR** [FransBouma/InjectableGenericCameraSystem#155]
Hi Frans, I'm old user from your mods. I would like to become Patreon, but I need to know if you already create a compatible version to Windows 11. Since I changed my OS from 10 to 11, your injection camera crash the game. Sadness.
Do you have a compatible version of camera to Windows 11?

**Comment by Fael78BR** [comment]
Hey Frans, sorry my delay. It's Carnival in Brazil ;-) The Game is Resident Evil 2 Remake, I intend to Patreon, all I need to know is your mod already have support to Windows 11. I'm playing with Non RT DirectX 11 in my PC.

**Comment by FransBouma** [comment]
that should work fine
