### ISSUE TITLE
[Elden ring] how to move a character while the camera is on?

### ISSUE THREAD

**Issue by venomg69** [FransBouma/InjectableGenericCameraSystem#156]
While the camera is on, you cannot move the character, I would like the wasd and attack keys to work the same way at this time. How can I do this?

**Comment by FransBouma** [comment]
https://opm.fransbouma.com/faq.htm#i-want-to-move-the-character-when-i-enable-the-camera.-how-do-i-do-that

**Comment by venomg69** [comment]
Hmm, I click on the numeric pad, but I still can't move the character

**Comment by venomg69** [comment]
Hmm, I click on the numpad, but I still can't move the character

**Comment by FransBouma** [comment]
This repo isn't for feedback on my camera tools that are only on my patreon. You have to enable input to the game, as described in the doc page. The `Numpad .` key will enable input to the game from kb/mouse.
