### ISSUE TITLE
Hitman: Broken again on latest update

### ISSUE THREAD

**Issue by notexe** [FransBouma/InjectableGenericCameraSystem#22]
Pressing INS results in nothing happening.

**Edit:** I think it's the 1.9.1 update, but it still says 1.9.0 in-game? Weird.

**Comment by FransBouma** [comment]
You do use DX11? Did you download v1.0.7 of the camera tools, uploaded yesterday? https://github.com/FransBouma/InjectableGenericCameraSystem/releases/tag/Hitman2016_v107 

I forgot to close this issue, it's tracking the breaking of v1.0.6 of the camera, which was fixed yesterday.

**Comment by Alessio7842** [comment]
Hi Frans, today IOI Interactive released a new update, do you have an ETA about the fix of your camerahack? Thank you very much!

**Comment by FransBouma** [comment]
what... I just updated the camera tools yesterday because of their update last friday!.

**Comment by FransBouma** [comment]
eta... 4-5 hours.

**Comment by FransBouma** [comment]
Hmm, my game hasn't updated yet, I see they roll out the update in phases, so I have to wait till the game updates from steam. Can't do much before that... I'll try as soon as I have time and the game is updated (which is hopefully within a couple of hours, otherwise it will be tomorrow).

**Comment by FransBouma** [comment]
See: https://github.com/FransBouma/InjectableGenericCameraSystem/releases/tag/Hitman2016_v108
