### ISSUE TITLE
Watchdogs 2 Camera has broken hotsampling after latest patch

### ISSUE THREAD

**Issue by FransBouma** [FransBouma/InjectableGenericCameraSystem#29]
The hotsampling AOB scan is currently broken

**Comment by Cyberim** [comment]
Hi Frans , do you have any plans to update WD2's camera tool ？

**Comment by FransBouma** [comment]
nope

**Comment by Cyberim** [comment]
What a pity, since I have a MOD that allows me to climb all tall buildings, I still want to use your camera tool to make some video...

**Comment by Cyberim** [comment]
Hi again,I see you're updating the old game. When's WD2?

**Comment by Cyberim** [comment]
I see it ! you are awesome!!!
