### ISSUE TITLE
Why the Hitman version says there are new versions of this program but I didn't see source code updated here?

### ISSUE THREAD

**Issue by vczh** [FransBouma/InjectableGenericCameraSystem#49]
Why the Hitman version says there are new versions of this program but I didn't see source code updated here?

By the way, the dialog seems doesn't want to popup twice. Now I cannot find the URL it told me to download ...

**Comment by FransBouma** [comment]
If I go to: https://github.com/FransBouma/InjectableGenericCameraSystem/tree/master/Cameras/Hitman2016

I can click the release link which brings me to the latest build of the tools. 

> By the way, the dialog seems doesn't want to popup twice. Now I cannot find the URL it told me to download ...

I don't know what you mean?

**Comment by vczh** [comment]
@FransBouma When the first time I run the program downloaded from exactly what your link pointing to, it prompted a dialog, telling me to download a new version from a website. I didn't open the website, the URL reads like a blog provider.

If you don't know what it is, maybe github was hacked.

**Comment by FransBouma** [comment]
You're in China? It might be the DNS was spoofed. In any case, download it from here directly: https://github.com/FransBouma/InjectableGenericCameraSystem/releases/tag/Hitman2016_v109
Hopefully that helps :)

**Comment by vczh** [comment]
I'm in the US. By the way, when the console window prompt, it prints:
```
All hooks enabled.
Can't find pattern for block 'AOB_CAMERA_READ_INTERCEPT3'! Hook not set.
Can't find pattern for block 'AOB_FOV_WRITE_INTERCEPT1'! Hook not set.
Can't find pattern for block 'AOB_FOV_WRITE_INTERCEPT2'! Hook not set.
One or more interception offsets weren't found: tools aren't compatible with this game's version.
Waiting for camera struct interception...
```
So if you have time you can take a look.

I am curious, do you need to reverse engineering the game to hack all of these things? Or you only use standard DirectX hook features?

**Comment by FransBouma** [comment]
I see they've patched the game again. The tools are for v1.10, but I see on steam they've released 1.12.1 in July. I did add AOB scanning (so it can find the code based on byte sequences) but apparently this failed for some parts. 

I'll see what I can do, but don't get your hopes up. I've uninstalled the game a long time ago. Reverse engineering of the game parts where the camera is used. These are then patched with a hook, i.e. they jump into the camera tools, which skips parts of the original assembler if the camera is enabled, see e.g. https://github.com/FransBouma/InjectableGenericCameraSystem/blob/master/Cameras/Hitman2016/InjectableGenericCameraSystem/Interceptor.asm

Blocks to hook are found here: https://github.com/FransBouma/InjectableGenericCameraSystem/blob/master/Cameras/Hitman2016/InjectableGenericCameraSystem/InterceptorHelper.cpp#L71
Hooks are set here: 
https://github.com/FransBouma/InjectableGenericCameraSystem/blob/master/Cameras/Hitman2016/InjectableGenericCameraSystem/InterceptorHelper.cpp#L106

so it's likely the byte sequence used for the 3 blocks that aren't found is different now.

**Comment by vczh** [comment]
Thank you

**Comment by vczh** [comment]
---------------------------
Extreme Injector v3
---------------------------
A new version of Extreme Injector has been detected (v3.7).

To obtain the latest version either visit the place where you downloaded the injector or head over to my blog page at:

masterscorner.wordpress.com
---------------------------
OK   
---------------------------

I got the dialog again. So is this intended?

**Comment by FransBouma** [comment]
You can ignore that. To download the v3.7 I had to register on that forum and I didn't want to, so I keep using the older version, which works fine.

**Comment by vczh** [comment]
@FransBouma So the GUI is Extreme Injector? I thought you made the whole thing so that you created that dialog, and wondering why I couldn't find the source code.

**Comment by FransBouma** [comment]
No the extreme injector injects the dll into the attached process, and contains some stealth code to do that. When it does that, the dll is attached to the process and then [this code](https://github.com/FransBouma/InjectableGenericCameraSystem/blob/master/Cameras/Hitman2016/InjectableGenericCameraSystem/Main.cpp#L47) runs, which starts up the rest. the hitman camera doesn't contain an in-game UI tho, only the last few cameras do, e.g. the MGS5 one and the Hellblade one.
