### ISSUE TITLE
[Hitman] DirectX12 support

### ISSUE THREAD

**Issue by hardware** [FransBouma/InjectableGenericCameraSystem#6]
Hi,

Do you plan to add Direct3D12 support in your injection tool for HITMAN™ game ?

_Great work and awesome tool btw ! Like it 👍 
It reminds me my work on a basic object viewer with [freecam system](https://github.com/hardware/ObjectViewer/blob/master/src/objects/camera.h) :)_ (study work)

**Comment by FransBouma** [comment]
:) 

I don't have windows 10 (only in a VM for other dev work) so supporting DX12 isn't possible at the moment and I don't see that change in the future soon. Sorry. Nice camera work btw!

**Comment by hardware** [comment]
But other contributors could add it :3

**Comment by FransBouma** [comment]
Ok. :)
