### ISSUE TITLE
Changing FOV outside the freecam doesn't work. 

### ISSUE THREAD

**Issue by Mistah47** [FransBouma/InjectableGenericCameraSystem#61]
Before I had the option to change the FOV while still having the camera locked onto 47 during gameplay. Doesn't work anymore. Pressing Insert only enables the freecam.

**Comment by FransBouma** [comment]
That's right. The fov code that previously worked didn't work anymore. So I spent half a day finding a different fov value which would work, however all values I found had a problem: disabling the code to write them would also remove the zoom weapon feature. This meant it would affect gameplay so I added it only when the camera is enabled.
