### ISSUE TITLE
Lords of the fallen injector insta crash

### ISSUE THREAD

**Issue by Issue12** [FransBouma/InjectableGenericCameraSystem#63]
I'll run the game and injector as admin the injector never shows on screen but under processes on task manager it shows up for a couple seconds before disappearing. Video showing what happens: https://youtu.be/D1oS0gK-xWY

**Comment by FransBouma** [comment]
Please try Extreme injector 3.72. Or try the injector packaged with the latest AC:Origins camera, and adjust the ini file to meet the needs of Lords of the fallen:

```ini
[InjectionData]
Process=LordsOfTheFallen.exe
Dll=LordsOftheFallenCameraTools.dll
```

and otherwise I don't know.
