### ISSUE TITLE
Alt+Tab = Main Menu

### ISSUE THREAD

**Issue by Zekirs** [FransBouma/InjectableGenericCameraSystem#67]
Hi, I wonder if there is a simple solution for when you pause the game with the Num 0 Button, choose the positioning for shotting and etc, but when you alt tab to turn on the SRWE custom res, the game goes to the main menu and the only way to close it is pressing Insert again, and returning to the desired position is kind hard with the srwe screen. I'm kinda new in these things, am I doing something wrong? There is a better way to deal with it? Thanks. Your Cam tool is incredible btw, great job!

**Comment by FransBouma** [comment]
I've never seen that, what game are you using? If you disable input (numpad . in some cameras) does that help?

**Comment by Zekirs** [comment]
It was on Doom, I found a way, instead of pressing Insert, I press Home to keep the camera locked, this way I don't lose my positioning. It is a great function, this camera lock.

**Comment by FransBouma** [comment]
Ah yes: the home key lock is especially meant for that situation: alt-tabbing away to srwe and back :) Also in games where it doesn't flip back to menu you need it as you might slightly move the mouse when going back to the game when alt-tabbing so I always lock when I go to srwe :) I'll close this for now as there's no other way to solve this :)
