### ISSUE TITLE
Watch Dogs 2 injector doesn't work

### ISSUE THREAD

**Issue by icarsis** [FransBouma/InjectableGenericCameraSystem#69]
I run it as admin and it doesn't open a console or nothing, nothing happens in game. I disabled EAC correctly the HUD correction works fine, but the injector doesn't work. same for ROTTR extreme injector just doesn't work for me, any fixes?

**Comment by FransBouma** [comment]
You have to click 'inject' in the extreme injector to inject the camera tools.
