### ISSUE TITLE
how do i make this to work?

### ISSUE THREAD

**Issue by elajits** [FransBouma/InjectableGenericCameraSystem#74]
where do i put the files to make it work? 
Thx!

**Comment by FransBouma** [comment]
I have no idea what you mean. What are the 'files' you refer to... please give more context.

**Comment by elajits** [comment]
Sry! I mean the Ansel /Camera for Dishonored! and how to use them!

**Comment by FransBouma** [comment]
You have to compile the code yourself, there's no binary. So if you don't know how to compile the code, then you can't use it, sorry :)
