### ISSUE TITLE
Signatures changes

### ISSUE THREAD

**Issue by Smithfields** [FransBouma/InjectableGenericCameraSystem#76]
Hi,
Today's patch broke the camera (Along with Mooncrash update).
I suppose structures' signature are different now.
Any chance for fix?

Cheers.

<img width="674" alt="2018-06-11_10-57-44" src="https://user-images.githubusercontent.com/2913543/41226354-84bc6ef0-6d71-11e8-8ed0-1600bbc4cfe2.png">

**Comment by FransBouma** [comment]
I assume you're talking about 'Prey' ? No sorry, I'm not playing that game anymore (nor will I do that again) so I won't fix the camera tools for it. Sorry.
