### ISSUE TITLE
Hitman 2016 Timestop

### ISSUE THREAD

**Issue by htang014** [FransBouma/InjectableGenericCameraSystem#78]
I know this is no longer a supported game, but the tools do still work.  Just one problem:  After using the tool for about 30 mins the timestop tool (Num 0) suddenly stopped working, and neither reinstalling the game nor wiping my graphics drivers could restore it.

Any ideas on what I can delete to reset the tool?

**Comment by FransBouma** [comment]
You restarted the game and still timestop doesn't work? You didn't get any error? Not that I can do anything about it though. Very weird, I have no idea.
