### ISSUE TITLE
Tomb Raider 2013 Cheat Table

### ISSUE THREAD

**Issue by Keith94** [FransBouma/InjectableGenericCameraSystem#79]
Hi,

Sorry for off topic, but do you by chance have the original CT file created by jim2point0 (links on [DET](http://deadendthrills.com/forum/discussion/240/guide-tomb-raider) are dead)? Thanks.

**Comment by FransBouma** [comment]
You're posting this in the repository which has camera tools for this game: https://github.com/FransBouma/InjectableGenericCameraSystem/tree/master/Cameras/Tombraider :) 

Or are my tools lacking a feature that was in the table?

**Comment by Keith94** [comment]
Well, I was looking for FOV control during actual gameplay. Does yours have it?

**Comment by FransBouma** [comment]
Nope only during free cam (as stated on the download page: https://github.com/FransBouma/InjectableGenericCameraSystem/releases/tag/TombRaider2013_v101 

You can create a Cheat table yourself, from the offsets in the source: https://github.com/FransBouma/InjectableGenericCameraSystem/releases/tag/TombRaider2013_v101. This is to obtain the FoV address at runtime (see intercepter code here https://github.com/FransBouma/InjectableGenericCameraSystem/blob/master/Cameras/Tombraider/InjectableGenericCameraSystem/Interceptor.asm#L81 You need 2 write blocks. I guess you can simply nop them in your CT. 

(offsets from start of exe). Lower down in that file you see the offset of the FoV value related to the address intercepted.
