### ISSUE TITLE
Prey 2017 camera tools - Not Working

### ISSUE THREAD

**Issue by williammalakian** [FransBouma/InjectableGenericCameraSystem#81]
The injector dont work because the game version is different (I think they updated the game after Mooncrash release)

**Comment by FransBouma** [comment]
That's too bad, but I'm not going to update the camera for that game anymore, sorry. (I have uninstalled the game)

**Comment by williammalakian** [comment]
Right, thank you anyway - your camera tools are amazing :D

**Comment by FransBouma** [comment]
Thanks! :D
