### ISSUE TITLE
AC Odyssey time stop

### ISSUE THREAD

**Issue by ceekaysickart** [FransBouma/InjectableGenericCameraSystem#82]
When using the camera tool for AC Odyssey, the in-game timer automatically freezes. I wanted to do some timelapse videos but found out that the time is frozen and I'm only able to make it move forward by adjusting the cursor in the tool. However, the tool is then captured by any screen recording software and the timelapse isn't possible anymore.

**Comment by FransBouma** [comment]
This is a limitation of the game, as stated in the readme:

> Time of day and a paused game / cutscenes. 
> Time-of-day doesn't work in cutscenes, you'll get the time-of-day of the cutscene: the game simply doesn't respond to changes of the value during cutscenes. Time of Day also doesn't work when the game is paused, the sun position doesn't change in that situation. This is a limitation of the game. 

As you obviously read the readme, this isn't news to you of course.
