### ISSUE TITLE
Chunked frustum rendering ("Super resolution")

### ISSUE THREAD

**Issue by fakuivan** [FransBouma/InjectableGenericCameraSystem#84]
We could use the same method nvidia ansel uses to render higher-than-viewport-resolution screenshots by dividing the view frustum into different "chunks" and then stitching them into a single image. Figure stitching a panorama but without applying any image distortion. 

![image](https://user-images.githubusercontent.com/15100012/51629465-6b3eb200-1f26-11e9-9612-ee4321065479.png)

there will have to be some overlap between the chunks to allow for blending of things like lens flare and other screen space effects. 

https://computergraphics.stackexchange.com/questions/8500/modify-camera-matrix-so-that-it-renders-a-chunk-of-the-frustum

**Comment by FransBouma** [comment]
It's an interesting feature :) When I look at the Ansel SDK docs (available when you register with NVidia as a dev), they pass to the game the following:

```c
struct Camera
{
	Vec3 position;
	Quat rotation;
	float fov;
	float projectionOffsetX, projectionOffsetY;
	float nearPlane, farPlane;
	float aspectRatio;
};
```

The projectionOffsetX/Y are pre-sized and the docs say these have to be applied to the projection matrix of the game. I first thought they simply lower the fov to a low value (regular fov / # of chunks in the grid), reposition the camera (like how you'd do it manually) over a grid, but that indeed doesn't cut it. 

These 2 values are 'off-center' projection coordinates, so they have to be applied to the projection matrix, which is something we don't usually intercept (as changing the FoV is enough). They suggest the x/y values are added to the D3DXMatrix value's _31 and _32 values (added to it), the D3DXMatrix is obtained by the D3DXMatrixPerspectiveFovRH call. This isn't always the case however, games can use their own, so it's not going to work if they do (read: we then have to come up with a way to manipulate the projection matrix to get the same effect). Usually tho I think this is the same thing, depending on the handiness of the axis used (which is usually D3D's)

Ansel's SDK lists a lot of problems with this technique, one which isn't solvable (Screenbased reflections) and others which are to be taken care of by the dev (something we can't solve). 

There's another problem: currently I use reshade to apply post-processing, however with this technique the shaders need to know which grid element they're on and act accordingly. This means e.g. depth of field needs to be run inside IGCS as well. (which means shaders need to be ported, and a reshade-like pipeline has to be added). I thought about doing this some time ago (as it would be beneficial also if camera paths are added, you can then change effects per camera path node) but for now held that off as it's a lot of work.
