### ISSUE TITLE
Scriptable (?) multi-image lightfield capture

### ISSUE THREAD

**Issue by wormyrocks** [FransBouma/InjectableGenericCameraSystem#85]
Hi!

I've spent about a day playing around with [lightfield game capture](https://twitter.com/wormyrocks/status/1095837213336788992) for the [Looking Glass 3D display](https://www.lookingglassfactory.com) (i'm an employee there) and I'm interested in using a system like IGCS to get perfect screenshots rather than fumbling around in the developer console or worse, moving my character around in the game.
Our system is very similar to a stereo/parallax display, where you take two photos from slightly different angles and superimpose them to create a depth illusion, but rather than displaying 2 views it actually superimposes 45 images at once.
So - what's required for the image capture is actually very simple. All I need is a method through which I can repeatedly move the camera a fixed distance left and right, taking a screenshot each time. To set the distance between pictures, I'd ideally like to patch in an additional variable parameter which can be adjusted from the imgui. It looks like I just need to drop in a bit of extra code in Input.cpp and CameraManipulator.cpp to repeatedly call Camera::moveRight and Camera::moveLeft. But, as I need to save an image between every movement, I don't know if there is a straightforward way to dump framebuffer to image directly from the injected code? Ideally this capture process would be near-instant, so I wouldn't need to press the screenshot button 45 times for it to work.
I'm happy to hack at the source code a little bit, but I'm wondering if there's anything I should be aware of that might make the process easier, i.e., unimplemented functions that dump framebuffer to file, or a way to move the camera to an exact position relative to its current one. I noticed you were planning a feature [basically identical to this idea](https://github.com/FransBouma/InjectableGenericCameraSystem/issues/43) in another issue, and this seems like a simpler version of that as we don't need to account for a curved path or smooth motion.
This is a really amazing project and I'm super excited to get some amazing 3D captures, so thanks for working on it!

**Comment by FransBouma** [comment]
Hey :)

That sounds like a great little project! :) For moving the camera for an x amount, you indeed can use moveleft/right on the camera class. Just call the method and the camera will move. The mainLoop (https://github.com/FransBouma/InjectableGenericCameraSystem/blob/master/Cameras/AssassinsCreedOdyssey/InjectableGenericCameraSystem/System.cpp#L72) first handles user input and then writes the new camera info to the struct in memory. This means if you call moveleft/right on the camera instance, the new values will be written to the camera struct in memory after updateFrame has ran. 

This week I've added keybinding support to the newest camera iteration, which is the AC:Odyssey camera, so I'd use that source as the base of your changes. 

The amount to move left/right could be configurable through imgui indeed. I'd add the setting to the settings.h file (which has been factored out in this camera and all new ones moving forward) -> https://github.com/FransBouma/InjectableGenericCameraSystem/blob/master/Cameras/AssassinsCreedOdyssey/InjectableGenericCameraSystem/Settings.h#L28

A simple float will do. Then to edit the value, add a slider here, similar to the ones you see there: https://github.com/FransBouma/InjectableGenericCameraSystem/blob/master/Cameras/AssassinsCreedOdyssey/InjectableGenericCameraSystem/OverlayControl.cpp#L291
You don't need to mark settings dirty if it's not persisted to the ini file. 

I think that covers the camera side/editing. You of course want to take screenshots automatically. IGCS doesn't have that built-in as I use afterburner or reshade for that. However, you could add it to your project without much problems, e.g. by basing it on the save screenshot code in reshade's sourcecode: https://github.com/crosire/reshade/blob/master/source/runtime.cpp#L963 start there and follow the calls to other code you might need, like capture_frame(vector). It basically copies the framebuffer to an in-memory buffer and writes it to disk in a format, using stbi* functions, which are OSS functions for dealing with texture data. 

The camera paths issue is still on my radar (as well as adding a reshade-like layer to IGCS as reshade doesn't support Dx12 and I miss my DoF shader in dx12 games ;)) but not enough time at the moment to implement it in full. 

Hope this helps and if you have any further questions, let me know :)

**Comment by wormyrocks** [comment]
Sounds great! Is it plug and play to update less up-to-date games in the list with the newest camera code bindings, and if so, would you be able to let me know which C++ files to copy and which ones to leave alone? Right now I only own Prey, DOOM and MGS5.

**Comment by wormyrocks** [comment]
Implemented everything as described, and it all works great, except figuring out how to port in the capture_frame code from reshade! I'm very much not up to speed on how modern rendering engines work so I'm not sure how deep into the reshade code I should be digging to import headers, etc... is there an easy pointer to the framebuffer that's already exposed in IGCS?

**Comment by wormyrocks** [comment]
Actually - it seems to me that rather than porting in code from reshade, the easiest way to handle this would just be to spoof an F12 keydown message to use Steam's builtin screenshot function, since you're already hooking all the input reports. That code is a little opaque to me - do you have any advice on the quickest way to hack that in? Ideally in a way that ignores the input blocked state? Thanks!

**Comment by FransBouma** [comment]
The keybindings are more for configuring them at runtime, if you're fine with the defaults, you don't need those :) 

If you want to trigger capture code in another overlay, you have send a WM_INPUT or similar message to the window I think, to make them think a key is pressed. I haven't tried that tho. The hWnd to send the message to is here: https://github.com/FransBouma/InjectableGenericCameraSystem/blob/master/Cameras/AssassinsCreedOdyssey/InjectableGenericCameraSystem/Globals.h#L76 You can use Win32's SendMessage for that. 

Grabbing the backbuffer indeed requires the knowledge of which texture is the backbuffer and copy that to a buffer in-memory. The D3D11 device is available tho: https://github.com/FransBouma/InjectableGenericCameraSystem/blob/master/Cameras/AssassinsCreedOdyssey/InjectableGenericCameraSystem/UniversalD3D11Hook.cpp#L34 I hook d3d11 to get these. It's however rather straightforward I think, see: https://www.unknowncheats.me/forum/direct3d/74570-dx11-screenshot.html

Having that backbuffer you can then write it to a file using either png or bmp functions, see: https://github.com/nothings/stb

**Comment by wormyrocks** [comment]
After a couple attempts to adapt both the original reshade source and the unknown cheats method to get the backbuffer, I must admit defeat and come back with my code that exposes an embarassing lack of understanding of DirectX internals... :(
https://gist.github.com/wormyrocks/31317a3b694d0df4c1f23eee1d473a45#file-universald3d11hook-cpp-L219
This is my modification to UniversalD3D11Hook.cpp, it gives me a sequence of empty screenshot files. -- no dimensions, no data. capture_frame_() is my attempt to port capture_frame over from reshade, while capture_frame() is my attempt to port it from unknowncheats. (The latter crashes before it saves any files.) I imagine there is something very obviously wrong with this that ought to be an easy fix - any pointers?
Full repository reflecting all changes to code can be found [here](https://github.com/wormyrocks/InjectableGenericCameraSystem). Please excuse my terrible hacky code, I am extremely shaky with C++.
Thanks so much again for all your help!

**Comment by FransBouma** [comment]
Hey,

It could be you're copying the buffer right after it's cleared after vsync. Try to write a screenshot in the render loop, so right BEFORE present: https://gist.github.com/wormyrocks/31317a3b694d0df4c1f23eee1d473a45#file-universald3d11hook-cpp-L116

I haven't looked at reshade how that's doing it, but I guess this is needed, after present the buffers swap and you likely come in at a random moment, so there's no sync between what's on screen and your screenshot call. 

So what I'd do, is, when a screenshot needs to be taken, you set an atomic bool, in the present function (see link above) you check that bool, if it's true, you write a screenshot (or at least, copy the buffer, then hand it to a thread that writes the file, otherwise you get a serious stutter 😉), set the bool to false again and proceed as normal.

I haven't done this before tho, so I might be completely wrong, but I think that's what's going on. 

Good luck 😊

	Frans
