### ISSUE TITLE
Does this project support Hitman™ 2?

### ISSUE THREAD

**Issue by vczh** [FransBouma/InjectableGenericCameraSystem#86]
Does this project support Hitman™ 2?

**Comment by FransBouma** [comment]
Nope, sorry

**Comment by vczh** [comment]
Are you going to support it in some day?

**Comment by FransBouma** [comment]
I was planning to, did a day of research but then they released a new update and I could start all over again as everything changed. I wasn't planning to buy the game anyway (I used the 2.0 update for hitman1 which has the same exe) and it was basically the same thing as hitman1: a lot of updates that break the camera and as I wasn't going to use it myself I didn't want to go through that burden again.

**Comment by vczh** [comment]
The game has been released for almost an year, did you change your mind?

**Comment by FransBouma** [comment]
No, sorry :)
