### ISSUE TITLE
DMC5's camera doesn't seem to work with 21:9 patch

### ISSUE THREAD

**Issue by railgunpoi** [FransBouma/InjectableGenericCameraSystem#88]
it can only set the fov or pause the game etc,but it can't controll the camera position,I think it's because of the 21:9 patch I'm using but I'm not sure

**Comment by FransBouma** [comment]
Use the official steam exe, not the one without denuvo

**Comment by railgunpoi** [comment]
> Use the official steam exe, not the one without denuvo
thanks,but the steam version one's 21:9 patch hasn't updated yet,guess I gotta wait

**Comment by FransBouma** [comment]
The camera tools give you the choice of aspect ratio in the overlay, including 21:9 and also 'fit' which resizes the viewport to the size of the window so you can use SRWE to resize the window to whatever you want
