### ISSUE TITLE
Assassin's Creed Odyssey Camera version 1.0.6 doesn't work

### ISSUE THREAD

**Issue by Revolvere** [FransBouma/InjectableGenericCameraSystem#90]
Hello good sir,

First off I would like to thank you for your incredible work. IMO you are not the hero we deserved but the hero we needed :)

I've used your previous camera system for AC Odyssey in the past to great effect. Unfortunately, camera version 1.0.6 does not work properly as it did before. The camera tools window does not function with Ctrl-Ins along with several other controls. I've tried this in Fullscreen, Windowed mode and Borderless mode. The only hotkey that works for me is Numpad 0 which pauses the game. I appreciate everything that you do for the community. Is this something that you can look in to when you have the time? I know that you are incredibly busy and that these camera mods are only a hobby for you. Any help is much appreciated. Thank you so much!

**Comment by FransBouma** [comment]
Try to inject the camera as late as possible, e.g. when the level is already loaded. The copy protection decrypts parts of the code at runtime and it might not find the right hooks if you inject too early. It's odd that ctrl-ins doesn't function tho. I can't reproduce it, here it works fine with the latest update of the game. 

Also, if nothing helps, try to remove the igcs*.ini files in the game folder (not the one for the injector ;)) and try again. I got a report yesterday that the timestop didn't work but all other options did, restarting the game did fix it, so I have no idea what's wrong other than that the game engine decrypts part of the game at runtime and at the time of injecting some parts aren't there yet.

**Comment by Revolvere** [comment]
My apologies for the delayed response. This may sound strange but we've been having bad weather this past week and my internet has been out the last few days. Once I'm back in action I'll see if your solution works. Thanks for the reply!

**Comment by FransBouma** [comment]
Fixed
