### ISSUE TITLE
Game Crashes when Injecting the tool DX11 (Devil May Cry 5 Camera Tool)

### ISSUE THREAD

**Issue by itsadrianjosue** [FransBouma/InjectableGenericCameraSystem#91]
Game just crashes everytime I want to inject the tool. The game is set to Dx11 how the tutorial indicates.

**Comment by FransBouma** [comment]
and you run both the game and the injector as admin? You have a retail version and not a pirated copy? You're using the official steam exe and not the denuvo stripped one? 

If all answers are YES then it should work, if some of them are NO, then you know what to fix. I haven't heard any people saying the tools are broken for the latest version, so it should work properly.

**Comment by itsadrianjosue** [comment]
I'm using the retail version of the game from steam. I have though replaced the normal .exe for the denuvo stripped one. I'll try using again the normal one to see what happens. Thank you for answering!

**Comment by itsadrianjosue** [comment]
Update: "DMC5 Denuvo-free.exe" was causing the problem after replacing the .exe for the original steam one, everything worked as normal again.

**Comment by FransBouma** [comment]
👍

**Comment by cad5150** [comment]
Hi, I am having a issue with the tool. Game crashes with error "failed to get device from hooked swapchain" "failed to get device context from hooked swapchain". I am running steam verision.

**Comment by FransBouma** [comment]
use dx11
