### ISSUE TITLE
How to keep game time passing without pausing in photo mode

### ISSUE THREAD

**Issue by ArnoDorianWK** [FransBouma/InjectableGenericCameraSystem#92]
Hello, great author, I really like the camera tools you made, I want to use it to make some time-lapse video in 'Assassin's Creed: Origins', but when I press 'INS' to open photomode,  almost everything in the game is still moving but time seems to stop, like the sun or the moon in the sky, they stop moving, so I want to ask you how to keep the time moving when I open the photomode. My question is based on Assassin's Creed: Origins camera tools (v1.51+, UPlay). Finally, thank you very much for making such a great tool. I am a programming idiot and I am sorry for my bad English.Looking forward to your reply  .   Really appreciate.

**Comment by ArnoDorianWK** [comment]
Thank you very much for your reply.
Yes, in the game, the time of day function works fine, but once I turn on photomode or open the camera tool's 'settings menu', the time stops. But if I open the camera tool menu without opening the photo mode, then the time will stop in the 'settings menu', but in the 'console menu', 'help menu' and 'about menu' the time is moving normally. This makes me wonder.  So I guess if this 'time of day' function in the 'settings menu' caused the time stop in the photomode and camera tool 'settings menu'  ，because it has the function of adjusting the time.  I have tried many times and determined the existence of this problem. I hope that I can clearly explain the situation. I am very sorry if you find it difficult to understand.

**Comment by FransBouma** [comment]
Ah I think I see what the problem is: when the camera is enabled, I disable the writes to the timeofday variable so the game can't write to it. I do this because it might otherwise be a bit difficult to setup the perfect shot with e.g. shadow, if it moves away due to time of day. 

In your particular case, this is problematic as you don't want this. The only way to fix this is that I add an option for this, but as I don't have the game installed anymore, I can't test it if it works. So to make this work, I have to download the game again from uplay, add the feature, then test it and upload a new camera. Not sure I have the time for that.

**Comment by ArnoDorianWK** [comment]
Once again, thank you very much for your patience. My behavior is likely to have disturbed your normal work. I am very sorry about this. My thoughts are exactly the same as you said, about adding an option to this tool, but this requirement is selfish and will add a lot of trouble to you, sorry again for my reckless request . For me to be a programming idiot, you are really an approachable person, huge thanks.

**Comment by FransBouma** [comment]
No worries. I don't know how much this is worth to you, so I tell you what: you get me A Plague Tale: Innocence and I'll add that option for you a.s.a.p.

**Comment by ArnoDorianWK** [comment]
Wow, this news is really great for me, thank you very much for your help, I am very willing to use this game to exchange your help.

**Comment by ArnoDorianWK** [comment]
But sorry, I can't understand the email address you wrote. Do you want me to buy it on steam or what other way? I am in China, so I don't know if it will cause any trouble in purchasing.

**Comment by ArnoDorianWK** [comment]
Do you mean the address is frans@sd.nl?

**Comment by FransBouma** [comment]
haha yes. Now it's in plain sight in a public forum. I'll remove it in your post 😄

**Comment by ArnoDorianWK** [comment]
okok i'm sorry for that   i'll try to use the email to contact you.

**Comment by ArnoDorianWK** [comment]
I just wrote an email to the address you provided, not sure if you received it.
