### ISSUE TITLE
Dying Light has updated

### ISSUE THREAD

**Issue by Sparktank** [FransBouma/InjectableGenericCameraSystem#95]
They had an update recently to Patch 1.18.
Decided to try the camera tool since DL2 debuted at E3 show.

Under the console tab, it tells me I'm playing a different version of the game.
Not sure how to roll back to a previous version to use current camera tool.

**Comment by FransBouma** [comment]
Hmm... why would they update a game that's so old... anyway, to roll back to a previous version, see this guide: https://framedsc.github.io/GeneralGuides/steam_update_guide.htm
