### ISSUE TITLE
BulletstormFCE doesn't remove crosshair and doesn't change FOV anymore

### ISSUE THREAD

**Issue by Mancubuss** [FransBouma/InjectableGenericCameraSystem#96]
Console log

```
All hooks enabled.
Can't find pattern for block 'AOB_CROSSHAIR_INTERCEPT'! Hook not set.
Can't find pattern for block 'AOB_FOV_INTERCEPT'! Hook not set.
One or more interception offsets weren't found: tools aren't compatible with this game's version.
Waiting for camera struct interception...
Camera found.
Couldn't write to process memory, so couldn't set hook.
Error code: 3e6
Couldn't write to process memory, so couldn't set hook.
Error code: 3e6
```

Using numpad +/- changes FOV for maybe value of 1, that's it. And crosshair remains in place.

![StormGame-Win64-Shipping 2019-07-12 00-09-32](https://user-images.githubusercontent.com/29070996/61085728-9fa51c80-a439-11e9-81ea-6db8b9c298bd.png)

**Comment by FransBouma** [comment]
The camera should work with the latest steam edition they released in 2017. I don't see a later version there, so not sure why it doesn't work. You use a pirated version? Then you have to get the real version from steam. 

If you have the latest version from steam, try rolling it back to an earlier version, see this guide: https://framedsc.github.io/GeneralGuides/steam_update_guide.htm

**Comment by FransBouma** [comment]
Ah, I see now the camera can't write to process memory. You have to run the game as administrator, same as the injector.

**Comment by Mancubuss** [comment]
Hi!

Thanks for the prompt response and the time you spent to dig into this for
me. I actually run both exe's as Admin, and still get that double message
in console. And I am proudly using Steam version :)

Shall try reverting to previous version though, thanks for the tip. Will
write back with results.

пт, 12 лип. 2019 о 09:17 Frans Bouma <notifications@github.com> пише:

**Comment by Mancubuss** [comment]
I see that the last commit for this camera was on 30 April 2017, and last
update to BS:FCE is of December 2017, so I am downloading an April version
from Steam Depot now.

Upd.: Indeed, using an older version helped - it does work now, even with
ReShade :) Thanks once again for an instruction on how to revert updates in
Steam, I didn't know I can.

So, anyway, since there was an update to BS:FCE since the release of the
camera, is there a chance you could update it too?

пт, 12 лип. 2019 о 09:17 Frans Bouma <notifications@github.com> пише:

**Comment by FransBouma** [comment]
As I don't have the game installed anymore, and won't play it again, I don't think I'll fix it, sorry :)
