### ISSUE TITLE
Just a Thank you

### ISSUE THREAD

**Issue by Forkinator** [FransBouma/InjectableGenericCameraSystem#98]
I've been searching every day for the last 3 weeks for a noclip mode  for Deus Ex Mankind Divided and have not had any luck. This is the next best thing and I just want to say thank you for creating this amazing tool and making it work with many games.  Would love to see a noclip mode for some games as well. Not sure how difficult it would be with the toolset + skills you have.  

I am kind of new to Github and do not know of another way  to contact someone  besides using the issues tab. 

Thanks again.

**Comment by FransBouma** [comment]
You're welcome :) Enjoy :) 

I've also created a console unlocker for  Unreal Engine 4 games, which works in many games and which allows you to enable the debug camera. See: https://framedsc.github.io/GeneralGuides/universal_ue4_consoleunlocker.htm
In case you have one of the many games supported by it ;)

**Comment by Forkinator** [comment]
Wow, you are quite talented!  I will definitely use the console unlocker as well as the Camera System. 

Thanks again. It's much  appreciated!
